kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: mysql
  namespace: test1
spec:
  strategy:
    type: Rolling
  replicas: 1 
  selector:
    app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
              protocol: TCP 
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: secret123 
          imagePullPolicy: Always
      restartPolicy: Always
